### ISSUE TITLE
Create UserStory

### ISSUE THREAD

**Issue by dan-gentile** [dan-gentile/gym-bro#2]
# I took this from Devin's post on Slack, just want to confirm that this is the scope of what we are trying to do. 

back-story: People have been stuck inside during covid and have found ways to utilize that extra time. One thing people have done is started working out.
problem: working out generally requires some instruction (or at least an exercise list), and can get very tedious planning out music to last through the workout.
solution: we have the user input the type of workouts they want, the duration of their workout, and a genre of music. we then take those inputs, create a workout playlist (could just be a text guide with a breakdown of different workouts for the type they wanted), and we create a playlist of random songs within the genre selected to total the time input (edited)

**Comment by Pungry** [comment]
Back-Story: People have been stuck inside during covid and have found ways to utilize that extra time. One thing people have done is started working out.
Problem: Working out generally requires some instruction (or at least an exercise list), and can get very tedious planning out music to last through the workout.
Solution: We have the user input the type of workouts they want, the duration of their workout, and a genre of music. We then take those inputs, create a workout playlist, and we create a playlist of random songs within the genre selected to total the time input.

AS A quarantined person who wants to work out
I WANT to easily make a customized workout with accompanying music
SO THAT I can work out with motivation.

MVP: Creates a random playlist of music and workout exercises.
